#!/usr/bin/env bash

if [ "$DEBUG" = 'yes' ] && [ "$DEBUG_SHELL" != 'no' ]; then
    set -x
fi

export REMOTE_XEN1_NODE=xen1
export REMOTE_AMD_NODE=amd
export REMOTE_ML_NODE=ml
export REMOTE_CLUSTER1_NODE=cluster1
export REMOTE_LOGAN_NODE=logan
export REMOTE_GRANT_NODE=grant
export REMOTE_MULTIGPU_NODE=multi-gpu
export REMOTE_SINGLEGPU_NODE=single-gpu

# Local tunneling ports that have been allocated.
export AMD_GDB_PORT=1235
export AMD_SSH_PORT=8686
export XEN1_GDBGUI_PORT=8888
export XEN1_SSH_PORT=8787
export XEN1_GDB_PORT=1234
export XEN1_GDB_MATHUNITTESTS_PORT=1236
export CLUSTER1_SSH_PORT=8181
export LOGAN_SSH_PORT=8282
export LOGAN_GDB_PORT=1238
export LOGAN_GDB_UNITTEST_PORT=1239
export LOGAN_GDB_UNITTEST_LOCAL_PORT=1240
export LOGAN_SNAKEVIZ_PORT=6226
export LOGAN_TENSORBOARD_PORT=6116
export LOGAN_JUPYTER_PORT=5757
export GRANT_SSH_PORT=8123
export GRANT_JUPYTER_PORT=8124
export MULTIGPU_JENKINS_PORT=8782
export MULTIGPU_GDB_PORT=1237
export MULTIGPU_SSH_PORT=8989
export SINGLEGPU_SSH_PORT=8125

export WIFI_LOW_BANDWIDTH_SSIDS=("SM-G900W8_1592")
